version: '2'

services:
  zookeeper:
    logging:
      driver: none
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    logging:
      driver: none
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
      - '29092:29092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
    depends_on:
      - zookeeper

  producer:
    image: openjdk:11-jdk
    volumes:
      - ./producer/target:/app
    env_file:
      - .env
    working_dir: /app
    command: java -jar producer.jar
    ports:
      - '8081:8081'
    depends_on:
      - kafka

  consumer:
    image: openjdk:11-jdk
    volumes:
      - ./consumer/target:/app
    env_file:
      - .env
    working_dir: /app
    command: java -jar consumer.jar
    ports:
      - '8082:8082'
    depends_on:
      - producer

  frequency-api:
    image: openjdk:11-jdk
    volumes:
      - ./frequency-api/target:/app
    env_file:
      - .env
    working_dir: /app
    command: java -jar frequency-api.jar
    ports:
      - '8080:8080'
    depends_on:
      - consumer

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local