version: '2'

services:
  zookeeper:
    logging:
      driver: none
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    logging:
      driver: none
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
      - '29092:29092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
    depends_on:
      - zookeeper

  tweet-exporter:
    build: ./tweet-exporter
    volumes:
      - ${HOME}/.m2:/root/.m2
      - ./tweet-exporter:/app
    env_file:
      - .env
    ports:
      - '8081:8081'
    depends_on:
      - kafka

  term-exporter:
    build: ./term-exporter
    volumes:
      - ${HOME}/.m2:/root/.m2
      - ./term-exporter:/app
    env_file:
      - .env
    ports:
      - '8082:8082'
    depends_on:
      - kafka

  frequency-api:
    build: ./frequency-api
    volumes:
      - ${HOME}/.m2:/root/.m2
      - ./frequency-api:/app
    env_file:
      - .env
    ports:
      - '8080:8080'

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    env_file:
      - .env

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local